spring:
  application:
    name: consumer
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: http://localhost:8848
        namespace: public

dubbo:
  registry:
    address: nacos://127.0.0.1:8848
    register: false
  metadata-report:
    address: nacos://127.0.0.1:8848
  config-center:
    address: nacos://127.0.0.1:8848
  protocol:
    id: dubbo
    name: dubbo
    port: -1
  scan:
    base-packages:
      - com.example.demo
  cloud:
    subscribed-services: provider*
  consumer:
    timeout: -1

server:
  port: 9090