
server:
  port: 9527

spring:
  application:
    name: spring-cloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: zuul9527.com
    perfer-ip-address: true

info:
  app.name: zuul-geteway

zuul:
  prefix: /testprefix
  ignored-services:
    - "*"
  routes:
    providermydept:
      path: /provider8001/**
      serviceId: springcloud-provider-dept