server:
  port: 10001

spring:
  application:
    name: springcloud-config-server
    # 连接远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/ikun0000/springcloudtest.git   # 不是使用ssh