
spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: demo
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.24.23.44:3306/test
    username: root
    password: 123456
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

server:
  port: 8080