
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
    - classpath:mybatis/mapper/dept_mapper.xml

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.10.246:3306/DB01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: springcloud-provider-dept-hystrix-8001   # 修改status描述信息
    prefer-ip-address: false      # Status在数鼠标hover时浏览器不显示ip地址

# 展示在Eureka的Status的info信息
info:
  app.name: provider-springcloud-01
  company.name: test01.com
